global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["api:8000"]

  - job_name: worker
    metrics_path: /
    static_configs:
      - targets: ["worker:8001"]
