auth_enabled: false
server:
  http_listen_port: 3100
common:
  path_prefix: /loki
storage_config:
  filesystem:
    directory: /loki/chunks
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
